### ISSUE TITLE
Measure Impact with Analytics

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/bitcointranscripts.github.io#39]
As far as I know we don't measure any analytics, which means that we don't know how many people are using the site thus the impact of the project. 

A few months ago, through some of [0xb10c](https://github.com/0xb10c)'s projects, I stumbled upon [umami](https://umami.is/), a simple, self-hosted, open-source alternative to Google Analytics. The setup is very easy and they even have a simple [one-click deployment to Heroku](https://umami.is/docs/running-on-heroku) which we could use with a free account to initially validate the idea. After having the server it just needs a tracking script that we can easily add to our Hugo setup.

The cool think we umami is that 

1.  After you setup your umami instance you can have unlimited websites and separate accounts. That's how I tested that this is working for bitcoin transcripts by using my own umami setup to get analytics from a local instance of this repository. 
2. You can create a shareable link in which everyone can see your website statistics. [This is the link](https://yumami.herokuapp.com/share/eCYOjV4w/Demo%20Bitcoin%20Transcripts) showing the analytics for my aforementioned demo.

You can see examples of umami at 

- The footer of https://bitcoin-dev.blog/ which also has a link for their publicly accessible statistics.
- The footer of https://miningpool.observer/ which just mentions the use of umami.

If we proceed with this idea, the implementation is the easiest part (minor code changes). We just need to figure out the logistics of the self-hosted setup, which as I said, we can avoid with a new account in Heroku.

**Comment by adamjonas** [comment]
I understand the urge to want to track, but I guess the question is for what purpose? What would the use of this data be?

**Comment by kouloumos** [comment]
If you devote time to something, don't you want to be aware of the impact that it has? This is an open repository of transcripts were each contribution is help for a collective effort of aggregating a valuable resource for the benefit of the community. I think that being somehow aware of how the community uses that resource gives an inside for future steps and improvements. 

In my mind, the data have two purposes. (1) Incentive for contributors, a way to see that their work has impact (people are reading their transcripts) thus continue contributing. (2) A way to measure the results of future changes/actions. 

My hypothesis is that more audience results to more contributors thus a better website and greater impact. 

That's more of a personal note, but if I'm dedicating time to something I want it to have the max possible impact, if it doesn't I'll try to improve it. But this needs data. You need data to confirm that people are using the website. And if that's not the case, you need data to validate future actions.
