### ISSUE TITLE
Rewriting history to remove ./public directory from git history

### ISSUE THREAD

**Issue by kouloumos** [bitcointranscripts/bitcointranscripts.github.io#40]
As I first mentioned [here](https://github.com/bitcointranscripts/bitcointranscripts.github.io/issues/34#issue-1121816014)(last paragraph) and then confirmed [here](https://github.com/bitcointranscripts/bitcointranscripts/pull/127#issue-1167349967)(last paragraph), the `./public` directory is redundant and needs to be removed from source control. 

### Overview 
The problem is that we cannot just delete the directory as it will continue to be part of the git history. The way to remove the directory (and its contents) from every commit is to rewrite history. There are [multiple per-case ways to rewrite history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and numerous solutions for our own case ([1](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository), [2](https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history/32886427#32886427)). 

The "issue" with rewriting history is that we cannot just make changes and submit a PR, because as you can see from my [demo-master-branch](https://github.com/kouloumos/bitcointranscripts.github.io), all the commits are replaced thus you must rewrite and then push the new history to the branch. That's the main reason I'm opening this issue as this cannot be solved with just a PR. 

### Solution
I have experience with simple cases of rewriting history (amend, rebase) but nothing like this. My research [showed](https://stackoverflow.com/a/61544937/5800072) that [git-filter-repo](https://github.com/newren/git-filter-repo/) is the easiest way to accomplish this and that's what I used for my [demo-master-branch](https://github.com/kouloumos/bitcointranscripts.github.io). 

What I did to test my solution is rewrite history on my fork's master branch and verify that the website is deployed correctly through github-actions and also locally. There seems to be no issue and that's why I am now proposing to repeat this process to remove `./public` directory from the git history of this repository. 

I am not sure that my access level allows to directly commit to the master branch thus allowing me to execute what I described. If there are issues with me doing this, @adamjonas could do it (I'll give further step by step instructions) and push the new history.

### Benefits
1. As this directory is not needed, the result is that this repository is much bigger than it should be. By running `git count-objects -vH` you can verify a size of 228.24 MiB which after the change is reduced to a size of 81.41 MiB 

2. This change opens the way to better document the process of building locally for future contributors. (https://github.com/bitcointranscripts/bitcointranscripts.github.io/issues/34)

**Comment by adamjonas** [comment]
This works and it's live. Thanks @kouloumos!
