### ISSUE TITLE
Recent regressions on the btctranscripts.com site

### ISSUE THREAD

**Issue by michaelfolkson** [bitcointranscripts/bitcointranscripts.github.io#44]
I recently visited the btctranscripts website and there are a couple of regressions amongst some nice improvements

- There is no link to browse by category (event type) on the homepage.
- You used to be able to click on subheaders of a transcript (this would give you a link to a specific section of the transcript) and all the subheaders were present on the right hand side which were also clickable. Now you can't do any of that. I definitely think getting a link to a section within a transcript is a priority as that link can be shared (including within other transcripts).

(I'm less bothered about the subheaders on the right hand side being removed but not being able to click on the subheader to get a link to that section of the transcript is definitely a regression imo)

**Comment by kouloumos** [comment]
@michaelfolkson in what device and browser do you see this behaviour? 
Cause my experience is not the same:

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/18506343/180973636-6dd3fd17-2bb7-4f42-8bae-0463872310a1.gif)

> You used to be able to click on subheaders of a transcript (this would give you a link to a specific section of the transcript)

I confirmed that this is not available atm, although I can't confirm that it was actually a functionality at some point. No change was made that could introduce this regression but I will investigate. 
You can still get the link to the specific section by clicking on the right hand side.

**Comment by michaelfolkson** [comment]
@kouloumos: Going to the site now most of those things I reported I'm no longer experiencing (The column of events on the left hand side is back and the column of subheaders of a transcript on the right hand side is back). It was on MacOS, Chrome. If you didn't make those changes that it is strange. Ok thanks, I'll close for now and reopen if I experience them again.
